### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Andrea** [Matthew-Davey/mercury-particle-engine#2]
Hi there

We are maintaining a fork of this (from when it was in codeplex) it would be cool to add a license to it? maybe MS-pl? Cant remember what it was in the past  :D
Cheers

**Comment by Matthew-Davey** [comment]
Hey Andrea! How are you?

I didn't know anyone was still using Mercury! It was indeed MS-pl in the old days - nowadays I guess I'd lean towards WTFPL v2 :)
